#!/bin/bash
set -euo pipefail

# seed-etcd.sh — runs AFTER etcd is healthy, seeds cluster config.
# Called by globular-seed-etcd.service (oneshot, runs once at boot).

SCYLLA_ADDR="${GLOBULAR_SCYLLA_ADDR:-}"
NODE_IP="${GLOBULAR_NODE_IP:-}"
PKI=/var/lib/globular/pki
ETCDCTL=/usr/lib/globular/bin/etcdctl

# Read endpoints from the file we wrote in entrypoint
ENDPOINTS=$(cat /var/lib/globular/config/etcd_endpoints | tr '\n' ',' | sed 's/,$//')

ETCD="$ETCDCTL --endpoints=$ENDPOINTS --cacert=$PKI/ca.crt --cert=$PKI/issued/services/service.crt --key=$PKI/issued/services/service.key"

echo "[seed] Waiting for etcd to be healthy..."
for i in $(seq 1 120); do
    if $ETCD endpoint health >/dev/null 2>&1; then
        echo "[seed] etcd healthy."
        break
    fi
    sleep 1
done

# Seed ScyllaDB hosts (only if configured)
if [ -n "$SCYLLA_ADDR" ]; then
    # Check if already seeded
    existing=$($ETCD get /globular/cluster/scylla/hosts --print-value-only 2>/dev/null || echo "")
    if [ -z "$existing" ]; then
        echo "[seed] Writing ScyllaDB hosts: $SCYLLA_ADDR"
        $ETCD put /globular/cluster/scylla/hosts "[\"$SCYLLA_ADDR\"]"
    else
        echo "[seed] ScyllaDB hosts already seeded: $existing"
    fi
fi

# Seed MinIO hosts (storage node IP)
# In production, MinIO runs on the storage node.
# Check all nodes for storage profile — node-2 is 10.10.0.12
existing=$($ETCD get /globular/cluster/minio/hosts --print-value-only 2>/dev/null || echo "")
if [ -z "$existing" ]; then
    echo "[seed] Writing MinIO hosts: 10.10.0.12"
    $ETCD put /globular/cluster/minio/hosts '["10.10.0.12"]'
fi

# Seed system config (domain, cluster_id, bootstrapped flag)
existing=$($ETCD get /globular/system/config --print-value-only 2>/dev/null || echo "")
if [ -z "$existing" ]; then
    CLUSTER_DOMAIN="${GLOBULAR_CLUSTER_DOMAIN:-quickstart.local}"
    echo "[seed] Writing system config (domain=$CLUSTER_DOMAIN, cluster_id=$CLUSTER_DOMAIN)"
    $ETCD put /globular/system/config "{\"Domain\":\"$CLUSTER_DOMAIN\",\"cluster_id\":\"$CLUSTER_DOMAIN\",\"bootstrapped\":true}"
fi

# Seed DNS hosts (control-plane node IPs)
existing=$($ETCD get /globular/cluster/dns/hosts --print-value-only 2>/dev/null || echo "")
if [ -z "$existing" ]; then
    echo "[seed] Writing DNS hosts: 10.10.0.11, 10.10.0.12, 10.10.0.13"
    $ETCD put /globular/cluster/dns/hosts '["10.10.0.11","10.10.0.12","10.10.0.13"]'
fi

# Seed cluster network spec so DNS reconciler generates A records.
# In production, this is written by the controller during bootstrap.
# The spec must include the cluster domain and node profile assignments.
existing=$($ETCD get /globular/clustercontroller/network-spec --print-value-only 2>/dev/null || echo "")
if [ -z "$existing" ]; then
    echo "[seed] Writing network spec (domain=globular.internal)"
    $ETCD put /globular/clustercontroller/network-spec '{"cluster_domain":"globular.internal"}'
fi

# Seed DNS A records for critical services directly.
# In production, the DNS reconciler generates these from node profiles.
# In the quickstart, we seed them explicitly to match the compose topology.
# MinIO runs on node-2 (storage profile).
existing=$($ETCD get /globular/cluster/dns/records --print-value-only 2>/dev/null || echo "")
if [ -z "$existing" ]; then
    echo "[seed] Writing DNS service records"
    $ETCD put /globular/cluster/dns/records '{
        "minio.globular.internal": "10.10.0.12",
        "gateway.globular.internal": "10.10.0.11",
        "controller.globular.internal": "10.10.0.11"
    }'
fi

# MinIO uses TLS (secure=true) — matching production. The MinIO container
# has cluster CA-signed certs generated by the entrypoint.

echo "[seed] etcd seeding complete."
